version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${minio_username}
      MINIO_ROOT_PASSWORD: ${minio_password}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${mongodb_port}:${mongodb_port}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongodb_username}
      MONGO_INITDB_ROOT_PASSWORD: ${mongodb_password}
    volumes:
      - mongo_data:/data/db

volumes:
  minio_data:
  mongo_data: 